site_name: Informatica Intelligent Data Management Cloud (IDMC)
site_description: Complete Open Source IDMC Course Repository
site_author: Hidam Rameshwar Singh

theme:
  name: material
  language: en

  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Course Outcomes: course-outcomes.md

  - Unit 1:
      - Overview: unit1.md

  - Unit 2:
      - Overview: unit2.md

  - Unit 3:
      - Overview: unit3.md

  - Unit 4:
      - Overview: unit4.md

  - References: references.md